# Generated by Django 5.1.3 on 2025-01-13 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventapasajes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ruta',
            name='duracion_aproximada',
        ),
    ]
