# Generated by Django 5.1.3 on 2025-01-13 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventapasajes', '0002_remove_ruta_duracion_aproximada'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario',
            name='costo_pasaje',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
