# Generated by Django 5.1.3 on 2025-01-13 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventapasajes', '0003_horario_costo_pasaje'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pasaje',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='pasaje',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='pasaje',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='pasaje',
            name='numero_asiento',
        ),
    ]
