# Generated by Django 5.1.3 on 2025-01-13 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventapasajes', '0005_pasaje_asiento_alter_pasaje_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pasaje',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='pasaje',
            name='asientos',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='pasaje',
            name='asiento',
        ),
    ]
