# Generated by Django 5.1.3 on 2025-01-14 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventapasajes', '0006_alter_pasaje_unique_together_pasaje_asientos_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reporte',
        ),
    ]
